apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: YYYY-rbd
provisioner: ceph.com/rbd
parameters:
  monitors: 10.10.2.180:6789
  adminId: admin
  adminSecretName: ceph-XXXX
  adminSecretNamespace: kube-system
  pool: kubernetes
  userId: kubernetes
  userSecretName: ceph-XXXX-kubernetes
  userSecretNamespace: kube-system
  imageFormat: "2"
  imageFeatures: layering
